services:
  mongo:
    image: mongo:7.0
    volumes:
    - mongo_data:/data/db
    restart: unless-stopped
  backend:
    build:
      context: ./backend
    environment:
      MONGO_URI: mongodb://mongo:27017
      MONGO_DB_NAME: snake_dev
    ports:
    - "19021:8000"
    depends_on:
    - mongo
    restart: unless-stopped
  frontend:
    build:
      context: ./frontend
    environment:
      VITE_API_BASE_URL: http://100.105.59.33:19021
    ports:
    - "19020:5173"
    depends_on:
    - backend
    restart: unless-stopped
volumes:
  mongo_data: null
